version: '3.7'
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
volumes:
  postgres_data2:
  redisdata:

networks:
  my_local:
    driver: host