name: OpenApi Schema PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout openapi schema
        uses: actions/checkout@v3
        with:
          repository: papermerge/openapi-schema
          path: openapi-schema

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          cd main
          poetry install
          cd docker/dev
          ./manage.py spectacular
